/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MemberSignIN;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.io.IOException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author 18559,18559,18562
 */
public class ClimateCare extends javax.swing.JFrame {

    /**
     * Creates new form ClimateCare
     */
    public ClimateCare() {
        initComponents();
    }
    
      public void close(){
       WindowEvent closing = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
       Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closing);
       
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        searchbtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        Templabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        warning1 = new javax.swing.JLabel();
        warning2 = new javax.swing.JLabel();
        warning3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MemberSignIN/climate_care_48px.png"))); // NOI18N
        jLabel3.setText("Climate Care");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 24, 312, 60));

        jButton1.setText("Sign Out");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(816, 12, -1, -1));

        jButton2.setText("Main Menu");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(816, 60, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MemberSignIN/2560x1440-dark-green-solid-color-background.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 912, 108));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Choose Location:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 132, -1, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 132, 240, -1));

        searchbtn.setText("Search");
        searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbtnActionPerformed(evt);
            }
        });
        getContentPane().add(searchbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(444, 132, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("Temperature:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        Templabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Templabel.setForeground(new java.awt.Color(240, 240, 240));
        Templabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Templabel.setText("0");
        getContentPane().add(Templabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 50, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setText("GlobalWarming:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, -1, -1));

        warning1.setForeground(new java.awt.Color(240, 240, 240));
        warning1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MemberSignIN/warning_48px.png"))); // NOI18N
        warning1.setText("jLabel8");
        getContentPane().add(warning1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 420, 50, -1));

        warning2.setForeground(new java.awt.Color(240, 240, 240));
        warning2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MemberSignIN/warning_48px.png"))); // NOI18N
        getContentPane().add(warning2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 420, -1, -1));

        warning3.setForeground(new java.awt.Color(240, 240, 240));
        warning3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MemberSignIN/warning_48px.png"))); // NOI18N
        getContentPane().add(warning3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 420, -1, -1));

        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MemberSignIN/climatecare.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 108, 912, 432));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        close();
        MemberSignIN edit= new MemberSignIN();
            edit.setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        close();
        MainMenu edit= new MainMenu();
            edit.setVisible(true);
            
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void searchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbtnActionPerformed
        try {
            // TODO add your handling code here:
            String location = jTextField1.getText();
            WeatherConditions s = new WeatherConditions();
            String temp = s.current3Temp(location);
            String url = "warning_48px.png";
            ImageIcon i = new ImageIcon(url);
            Templabel.setText(temp);
            if(temp.compareTo("44")>0 && temp.compareTo("44")==0){
                warning1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MemberSignIN/warning_48px.png")));
                warning2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MemberSignIN/warning_48px.png")));
                warning3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MemberSignIN/warning_48px.png")));
            }
            else if(temp.compareTo("44")<0 && temp.compareTo("30")>0){
                warning1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MemberSignIN/warning_48px.png")));
                warning2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MemberSignIN/warning_48px.png")));
                warning3.setIcon(null);
            }
            else 
             warning1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MemberSignIN/warning_48px.png")));
 
            warning2.setIcon(null);
                warning3.setIcon(null);
            
            
            
            
            
            
        } catch (ParseException ex) {
            Logger.getLogger(ClimateCare.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(ClimateCare.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_searchbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClimateCare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClimateCare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClimateCare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClimateCare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClimateCare().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Templabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton searchbtn;
    private javax.swing.JLabel warning1;
    private javax.swing.JLabel warning2;
    private javax.swing.JLabel warning3;
    // End of variables declaration//GEN-END:variables
}
